### ISSUE TITLE
Make "Name" required on sign-up

### ISSUE THREAD

**Issue by scotthue** [rdunlop/unicycling-rulebook#19]
Make the name field on the sign-up form (e.g. https://github.com/rdunlop/unicycling-rulebook/blob/a98329491a9f80105a9d43c66873dbb9e1892262/app/views/devise/registrations/new.html.haml) required.

**Comment by rdunlop** [comment]
Resolved with ce338ba9036ad4e40df082d1a0fad23194f6f11e
